version: "3.9"
services:
  test:
    build:
      context: .
    image: "exercise-1"
    volumes:
      - .:/app
    command: python3 -m pytest
  run:
    build:
      context: .
    image: "exercise-1"
    volumes:
      - .:/app
    command: python3 main.py
